# Generated by Django 4.2.5 on 2023-10-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_alter_menuitem_named_url_alter_menuitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
    ]
